folio-org/ui-linked-data

.github/workflows/ui.yml
.gitignore
jest.config.ts
package.json

[https://folio-org.atlassian.net/browse/UILD-404](https://folio-org.atlassian.net/browse/UILD-404)

UILD-404: CI - use default values for Sonar and translations compilation

---

src/App.tsx
src/common/api/base.api.ts
src/common/api/records.api.ts
src/common/constants/api.constants.ts
src/common/helpers/api.helper.ts
src/common/hooks/useContainerEvents.ts
src/common/hooks/useRecordControls.ts
src/components/Modal/Modal.tsx
src/components/ModalDuplicateImportedResource/ModalDuplicateImportedResource.scss
src/components/ModalDuplicateImportedResource/ModalDuplicateImportedResource.tsx
src/components/ModalDuplicateImportedResource/index.ts
src/components/PreviewExternalResourceControls/PreviewExternalResourceControls.tsx
src/components/PreviewExternalResourcePane/PreviewExternalResourcePane.tsx
src/state/config.ts
src/state/ui.ts
src/test/__tests__/common/api/base.api.test.ts
src/test/__tests__/common/api/records.api.test.ts
src/test/__tests__/common/helpers/api.helper.test.ts
src/test/__tests__/common/hooks/useContainerEvents.test.ts
src/test/__tests__/components/Nav.test.tsx
src/test/__tests__/components/PreviewExternalResourceControls.test.tsx
src/test/__tests__/components/PreviewExternalResourcePane.test.tsx
src/test/__tests__/views/ExternalResourcePreview.test.tsx
src/types/api.d.ts
src/views/ExternalResource/ExternalResourcePreview.tsx
src/views/Search/Search.tsx
translations/ui-linked-data/en.json

https://folio-org.atlassian.net/browse/UILD-408

feat: UILD-408: STORY: Continue

---

src/App.tsx
src/common/api/base.api.ts
src/common/constants/bibframe.constants.ts
src/common/helpers/api.helper.ts
src/common/helpers/progressBackup.helper.ts
src/common/helpers/record.helper.ts
src/common/helpers/recordFormatting.helper.ts
src/common/helpers/repeatableFields.helper.ts
src/common/hooks/useConfig.hook.ts
src/common/hooks/useResetRecordStatus.ts
src/common/services/recordToSchemaMapping/recordToSchemaMapping.service.ts
src/components/AdvancedSearchModal/AdvancedSearchModal.tsx
src/components/DateRange/DateRange.tsx
src/components/EditControlPane/EditControlPane.tsx
src/components/ErrorBoundary/ErrorBoundary.tsx
src/components/Modal/Modal.tsx
src/components/SimpleLookupField/SimpleLookupFilter.tsx
src/configs/complexLookup/complexLookupFilters.config.ts
src/embed.tsx
src/views/ExternalResource/ExternalResourcePreview.tsx

[https://folio-org.atlassian.net/browse/UILD-410](https://folio-org.atlassian.net/browse/UILD-410)

UILD-410: revise TODO comments and add corresponding Jira tickets

---

src/App.scss
src/common/constants/bibframeMapping.constants.ts
src/common/helpers/record.helper.ts
src/common/helpers/recordFormatting.helper.ts
src/common/hooks/useConfig.hook.ts
src/common/hooks/useProcessedRecordAndSchema.hook.ts
src/common/hooks/useRecordControls.ts
src/common/services/recordToSchemaMapping/recordToSchemaMapping.service.ts
src/components/EditPreview/EditPreview.tsx
src/components/EditSection/EditSection.scss
src/components/FullDisplay/PreviewContent.tsx
src/components/InstancesList/InstancesList.scss
src/components/InstancesList/InstancesList.tsx
src/components/Preview/Fields.tsx
src/components/Preview/Labels.tsx
src/components/Preview/Preview.scss
src/components/Preview/Preview.tsx
src/components/Preview/TitledPreview.tsx
src/components/PreviewActionsDropdown/PreviewActionsDropdown.tsx
src/components/Table/Table.tsx
src/test/__mocks__/common/hooks/useRecordControls.mock.ts
src/test/__tests__/common/helpers/record.helper.test.ts
src/test/__tests__/common/helpers/recordFormatting.helper.test.ts
src/test/__tests__/common/hooks/useProcessedRecordAndSchema.test.ts
src/test/__tests__/components/EditPreview.test.tsx
src/test/__tests__/components/InstancesList.test.tsx
src/test/__tests__/components/TitledPreview.test.tsx
src/views/Edit/Edit.scss
src/views/ExternalResource/ExternalResourcePreview.tsx
translations/ui-linked-data/en.json

https://folio-org.atlassian.net/browse/UILD-421

feat: UILD-421: STORY: Multiple instances per Work

---

src/common/hooks/useFetchSearchData.ts
src/components/EditSection/EditSection.tsx

[https://folio-org.atlassian.net/browse/UILD-405](https://folio-org.atlassian.net/browse/UILD-405)

UILD-405: reduce timeout of the debounced input and show status message after saving the record

---

src/components/EditPreview/EditPreview.tsx
src/test/__tests__/components/EditPreview.test.tsx

[https://folio-org.atlassian.net/browse/UILD-420](https://folio-org.atlassian.net/browse/UILD-420)

UILD-420: Fixed incorrect display of preview content

---

src/components/Comparison/Comparison.tsx

[https://folio-org.atlassian.net/browse/UILD-469](https://folio-org.atlassian.net/browse/UILD-469)

UILD-469: Clear comparison selection fix

---

src/components/Comparison/Comparison.tsx
src/test/__tests__/components/Comparison.test.tsx

[https://folio-org.atlassian.net/browse/UILD-472](https://folio-org.atlassian.net/browse/UILD-472)

UILD-472: Comparison fix - deselect checkboxes when deselecting a resource on the modal

---

src/App.scss
src/components/Dropdown/Dropdown.scss
src/components/SearchResultEntry/SearchResultEntry.tsx

[https://folio-org.atlassian.net/browse/TCR-50?focusedCommentId=245953](https://folio-org.atlassian.net/browse/TCR-50?focusedCommentId=245953)

TCR-50: resolve a11y issues

---

src/common/hooks/useLoadSearchResults.ts
src/test/__tests__/common/hooks/useLoadSearchResults.test.ts
src/views/Edit/Edit.tsx

[https://folio-org.atlassian.net/browse/UILD-484](https://folio-org.atlassian.net/browse/UILD-484)
[https://folio-org.atlassian.net/browse/UILD-481](https://folio-org.atlassian.net/browse/UILD-481)

UILD-484: Fix of incorrect requests for searching and editing records

---

src/common/hooks/useRecordControls.ts

[https://folio-org.atlassian.net/browse/UILD-487](https://folio-org.atlassian.net/browse/UILD-487)

UILD-487: show loader when importing resource from Inventory

---

src/common/constants/routes.constants.ts
src/common/helpers/navigation.helper.ts
src/test/__tests__/common/helpers/navigation.helper.test.ts
src/test/__tests__/views/Edit.test.tsx
src/views/Edit/Edit.tsx

[https://folio-org.atlassian.net/browse/UILD-481](https://folio-org.atlassian.net/browse/UILD-481)
[https://folio-org.atlassian.net/browse/UILD-487](https://folio-org.atlassian.net/browse/UILD-487)

UILD-481: fix for fetching incorrect resource

---

src/components/Comparison/Comparison.tsx
src/components/Pagination/Pagination.tsx
src/components/SearchResultEntry/SearchResultEntry.scss
src/test/__tests__/components/Pagination.test.tsx

[https://folio-org.atlassian.net/browse/UILD-471](https://folio-org.atlassian.net/browse/UILD-471)

UILD-471: Fixed pagination format for Comparison

---

src/common/hooks/useModalControls.ts
src/common/hooks/useSaveRecord.ts
src/common/hooks/useSaveRecordWarning.ts
src/components/ModalUncontrolledAuthorities/ModalUncontrolledAuthorities.scss
src/components/ModalUncontrolledAuthorities/ModalUncontrolledAuthorities.tsx
src/components/ModalUncontrolledAuthorities/index.ts
src/components/RecordControls/RecordControls.tsx
src/components/SaveRecord/SaveRecord.tsx
src/store/stores/ui.ts
src/test/__tests__/common/hooks/useSaveRecord.test.ts
src/test/__tests__/common/hooks/useSaveRecordWarning.test.ts
src/test/__tests__/components/ModalUncontrolledAuthorities.test.tsx
src/views/Edit/Edit.tsx
translations/ui-linked-data/en.json

[https://folio-org.atlassian.net/browse/UILD-451](https://folio-org.atlassian.net/browse/UILD-451)

UILD-451: Authority warning message displayed on save

---

src/common/constants/search.constants.ts
src/test/__tests__/components/AdvancedSearchModal.test.tsx

https://folio-org.atlassian.net/browse/UILD-489
Here were added default value for advanced search by "Title"

UILD-489: Order of indexes(follow-up)

---

src/components/ModalUncontrolledAuthorities/ModalUncontrolledAuthorities.scss

[https://folio-org.atlassian.net/browse/UILD-451](https://folio-org.atlassian.net/browse/UILD-451)

UILD-451: Authority warning message: styles fix

---

src/test/__tests__/views/Edit.test.tsx
src/views/Edit/Edit.tsx

[https://folio-org.atlassian.net/browse/UILD-510](https://folio-org.atlassian.net/browse/UILD-510)

UILD-510: Duplicate: Resource title is not changed when duplicating work/instance/and Instance is automatically linked to the duplicated Work

---

src/components/Accordion/Accordion.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Fields/Fields.tsx
src/components/Modal/Modal.tsx
src/components/SearchControlPane/SearchControlPane.tsx
src/components/Table/Table.tsx
src/providers/SearchProvider.tsx
src/providers/ServicesProvider.tsx
src/types/status.d.ts
src/types/uiComponents.d.ts

[https://folio-org.atlassian.net/browse/UILD-498](https://folio-org.atlassian.net/browse/UILD-498)

UILD-498: refactoring for React 19

---

src/common/helpers/schema.helper.ts
src/components/Preview/Fields.tsx
src/test/__tests__/common/helpers/schema.helper.test.ts

[https://folio-org.atlassian.net/browse/UILD-477](https://folio-org.atlassian.net/browse/UILD-477)

UILD-477: Fix: Work/Instance Full display and Comparison modal do not show repeated fields

---

src/common/hooks/useContainerEvents.ts
src/common/hooks/useRecordControls.ts
src/test/__tests__/common/hooks/useContainerEvents.test.ts
src/test/__tests__/components/PreviewExternalResourcePane.test.tsx

[https://folio-org.atlassian.net/browse/UILD-493](https://folio-org.atlassian.net/browse/UILD-493)

UILD-493: Fix - Instance Edit form: "Cancel" button does not cancel the action

---

CHANGELOG.md
src/components/Comparison/Comparison.scss
src/components/Comparison/Comparison.tsx
src/components/SearchResultEntry/SearchResultEntry.tsx

https://folio-org.atlassian.net/browse/UILD-475
Fixed layout of icons in comparison mode

UILD-475: Comparison Mode Refinement - Numbered icons(follow-up)

---

CHANGELOG.md
package.json
src/common/hooks/useConfig.hook.ts
src/components/Comparison/Comparison.tsx
src/components/Preview/Fields.tsx
src/components/Preview/Preview.tsx
src/test/__tests__/components/TitledPreview.test.tsx
src/types/record.d.ts

Added "selectedEntries" property to compared resources to properly render dropdown options. 
[https://folio-org.atlassian.net/browse/UILD-533](https://folio-org.atlassian.net/browse/UILD-533)

UILD-533: Enhance preview functionality by adding "selectedEntries" to relevant components and types

---

CHANGELOG.md
src/components/WorkDetailsCard/WorkDetailsCard.scss

[https://folio-org.atlassian.net/browse/UILD-529](https://folio-org.atlassian.net/browse/UILD-529)

UILD-529: Fix text alignment for details title in Search results set

---

CHANGELOG.md
src/embed.tsx
src/store/index.ts
src/store/utils/storeCreator.ts
src/test/__tests__/store/utils/storeCreator.test.ts

[https://folio-org.atlassian.net/browse/UILD-552](https://folio-org.atlassian.net/browse/UILD-552)

UILD-552: Clear global state on web component disconnection

---

CHANGELOG.md
src/views/Edit/Edit.tsx

[https://folio-org.atlassian.net/browse/UILD-553](https://folio-org.atlassian.net/browse/UILD-553)

UILD-553: Fix: Incorrect behavior when navigating between duplicated resources

---

CHANGELOG.md
src/common/constants/complexLookup.constants.ts
src/configs/complexLookup/complexLookup.config.ts

[https://folio-org.atlassian.net/browse/UILD-555](https://folio-org.atlassian.net/browse/UILD-555)
Updated profile:
[profile_monograph_v3.json](https://github.com/user-attachments/files/20792988/profile_monograph_v3.json)

UILD-555: Extended configs to add support for Subject of Work

---

src/common/services/recordGenerator/processors/profileSchema/groupProcessor.ts
src/test/__tests__/common/services/recordGenerator/processors/profileSchema/groupProcessor.test.ts

This PR fixes incorrect object structure generation for groups such as "Creator of Work", "Other Contributors", "Notes about Work", etc.
[https://folio-org.atlassian.net/browse/UILD-550](https://folio-org.atlassian.net/browse/UILD-550?focusedCommentId=267688&sourceType=mention%3FatlOrigin%3Dad4fa5dc8c2a4c05bdb77fb3f2ec5458)

UILD-550: Fix - Record generation - simplify group processing by creating a single group object

---

src/common/helpers/preview.helper.ts
src/common/helpers/record.helper.ts
src/components/Preview/ChildFields.tsx
src/components/Preview/Fields.tsx
src/components/Preview/preview.types.ts
src/components/Preview/preview.wrappers.tsx
src/test/__tests__/common/helpers/preview.helper.test.ts
src/test/__tests__/components/Preview/ChildFields.test.tsx

[https://folio-org.atlassian.net/browse/UILD-550](https://folio-org.atlassian.net/browse/UILD-550)

UILD-550: Fix - corrupted read-only sections layout

---

src/common/services/recordNormalizing/recordProcessingCases.ts
src/common/services/recordNormalizing/recordProcessingMap.ts
src/common/services/recordToSchemaMapping/recordToSchemaMapping.service.ts
src/test/__tests__/common/services/recordNormalizing/recordProcessingCases.test.ts

https://folio-org.atlassian.net/browse/UILD-584
Using a record with a controlled creator but all uncontrolled subjects, this is the new display (note the warning icons next to subject labels):
Saving also prompts a modal asking whether to proceed with uncontrolled authorities:

UILD-584: Assign subject of the work at Work Edit display - Uncontrolled Authorities

---

src/components/SearchResultEntry/SearchResultEntry.scss

https://folio-org.atlassian.net/browse/UILD-579 - from QA, see comments.

UILD-579: Fix: Correct instance focus border radius

---

src/components/InstancesList/InstancesList.tsx
src/test/__tests__/common/hooks/useNavigateToCreatePage.test.ts
src/test/__tests__/components/ProfileSelectionManager.test.tsx

Added types assertion and removed unused imports.
[https://folio-org.atlassian.net/browse/UILD-576](https://folio-org.atlassian.net/browse/UILD-576)

UILD-576: Fix for broken tests

---

CHANGELOG.md
src/common/constants/bibframeMapping.constants.ts
src/common/services/recordGenerator/schemas/profiles/instance.schema.ts

Add Publication frequency dropdown to Serials profile.

UILD-618: Add support for publication frequency

---

CHANGELOG.md
src/components/EditSection/DrawComponent.tsx
src/test/__tests__/components/EditSection.test.tsx

https://folio-org.atlassian.net/browse/UILD-630
Requires https://github.com/folio-org/mod-linked-data/pull/303 for correct constraint values.

UILD-630: Implement editable literal field flag

---

src/components/MarcTooltip/MarcTooltip.scss

[https://folio-org.atlassian.net/browse/UILD-538](https://folio-org.atlassian.net/browse/UILD-538)

UILD-538: Fix - Add margin to Marc Tooltip wrapper for improved layout
