folio-org/ui-linked-data

src/common/constants/bibframe.constants.ts
src/common/constants/bibframeMapping.constants.ts
src/common/helpers/common.helper.ts
src/common/helpers/record.helper.ts
src/common/services/recordNormalizing/recordProcessingMap.ts

[https://folio-org.atlassian.net/browse/UILD-410](https://folio-org.atlassian.net/browse/UILD-410)

UILD-410: update URIs to fix Sonar security hotspots

---

src/common/constants/bibframe.constants.ts
src/common/helpers/common.helper.ts
src/common/hooks/useProfileSchema.ts
src/common/services/recordToSchemaMapping/recordToSchemaMapping.service.ts
src/common/services/schema/schemaWithDuplicates.interface.ts
src/common/services/schema/schemaWithDuplicates.service.ts
src/components/DuplicateGroup/DuplicateGroup.tsx
src/components/DuplicateGroupContainer/DuplicateGroupContainer.tsx
src/components/DuplicateSubcomponentContainer/DuplicateSubcomponentContainer.tsx
src/components/EditSection/EditSection.tsx
src/components/FieldWithMetadataAndControls/CompactLayout.tsx
src/components/FieldWithMetadataAndControls/ExtendedLayout.tsx
src/components/FieldWithMetadataAndControls/FieldWithMetadataAndControls.tsx
src/components/Fields/Fields.tsx
src/state/config.ts
src/state/ui.ts
src/test/__mocks__/common/hooks/useServicesContext.mock.ts
src/test/__tests__/common/hooks/useProfileSchema.test.ts
src/test/__tests__/common/services/schema/schemaWithDuplicates.service.test.ts
src/test/__tests__/components/DuplicateGroup.test.tsx
src/test/__tests__/components/DuplicateGroupContainer.test.tsx
src/test/__tests__/components/DuplicateSubcomponentContainer.test.tsx
src/test/__tests__/components/EditSection.test.tsx
src/types/render.d.ts

https://folio-org.atlassian.net/browse/UILD-299

feat: UILD-299: STORY: Repeatable fields | Delete function

---

src/common/api/records.api.ts
src/common/constants/api.constants.ts

[https://folio-org.atlassian.net/browse/UILD-428](https://folio-org.atlassian.net/browse/UILD-428)

UILD-428: update API URLs

---

README.md

https://folio-org.atlassian.net/browse/UILD-409

feat: UILD-409: Write installation documentation for ui-linked-data module

---

src/common/constants/uiControls.constants.ts
src/components/FullDisplay/PreviewContent.tsx
src/components/Preview/Fields.tsx
src/components/Preview/Labels.tsx
src/components/Preview/Preview.scss
src/test/__tests__/components/FullDisplay.test.tsx

[https://folio-org.atlassian.net/browse/UILD-446](https://folio-org.atlassian.net/browse/UILD-446)

UILD-446: Edit headers in full entity display screens

---

src/common/constants/bibframe.constants.ts
src/common/helpers/schema.helper.ts
src/common/services/schema/schemaWithDuplicates.service.ts
src/components/Fields/Fields.tsx
src/test/__tests__/common/helpers/schema.helper.test.ts
src/test/__tests__/common/services/schema/schemaWithDuplicates.service.test.ts

[https://folio-org.atlassian.net/browse/UILD-452](https://folio-org.atlassian.net/browse/UILD-452)

UILD-452: fix for "Creator of Work"/"Other contributors" fields are not shown for the resource

---

src/components/SearchResultEntry/SearchResultEntry.tsx
src/test/__tests__/components/SearchResultEntry.test.tsx
src/test/__tests__/views/Search.test.tsx
src/views/Search/Search.tsx

[https://folio-org.atlassian.net/browse/UILD-468](https://folio-org.atlassian.net/browse/UILD-468)

UILD-468: Comparison fix - close comparison modal and clear selected checkboxes on Search page unmount

---

src/components/Comparison/Comparison.tsx
src/test/__tests__/components/Comparison.test.tsx

[https://folio-org.atlassian.net/browse/UILD-470](https://folio-org.atlassian.net/browse/UILD-470)

UILD-470: Comparison fix - resource is shown in full view when removing one out of three from the second page of comparison modal

---

src/components/Comparison/Comparison.tsx
src/components/SearchControls/SearchControls.tsx
src/test/__tests__/components/Comparison.test.tsx
src/test/__tests__/components/SearchControls.test.tsx

[https://folio-org.atlassian.net/browse/UILD-483](https://folio-org.atlassian.net/browse/UILD-483)

UILD-483: Fix: Comparison modal stays opened when all the resources removed from comparison

---

src/common/hooks/useLoadSearchResults.ts
src/common/hooks/useSearch.ts
src/components/AdvancedSearchModal/AdvancedSearchModal.tsx
src/test/__tests__/common/hooks/useLoadSearchResults.test.ts

[https://folio-org.atlassian.net/browse/UILD-484](https://folio-org.atlassian.net/browse/UILD-484)

UILD-484: fix of incorrect search requests

---

src/common/constants/search.constants.ts
src/components/EditControlPane/EditControlPane.tsx

https://folio-org.atlassian.net/browse/UILD-490
https://folio-org.atlassian.net/browse/UILD-489
Here we hide unused action dropdown items. Also, the order of items in the search(basic and advanced) was changed.

UILD-490: Clean Up: Action Drop Down Menu.

---

src/components/ModalSwitchToNewRecord/ModalSwitchToNewRecord.tsx

[https://folio-org.atlassian.net/browse/UILD-501](https://folio-org.atlassian.net/browse/UILD-501)

UILD-501: Fix - 'Continue without saving' is disabled on the modal shown when switching to work from duplicated instance with unsaved changes

---

src/components/Comparison/Comparison.scss
src/components/Comparison/Comparison.tsx
src/components/SearchResultEntry/SearchResultEntry.tsx

https://folio-org.atlassian.net/browse/UILD-475
We added numbered icons inside the panes for comparison mode. Also, in the scope of that ticket were fixed bugs with reversed order of comparison indexes. https://folio-org.atlassian.net/browse/UILD-473
https://github.com/user-attachments/assets/47a5c36e-48d4-4198-81d1-92bd20d7cfcf

UILD-475: Comparison Mode Refinement - Numbered icons

---

src/common/constants/api.constants.ts
src/common/helpers/api.helper.ts
src/common/hooks/useRecordControls.ts
translations/ui-linked-data/en.json

https://folio-org.atlassian.net/browse/UILD-508
We added error handling for `linked-data/resource` endpoint based on error codes to provide more user-friendly error toasts.

UILD-508: Error messages to display on LDE

---

CHANGELOG.md
src/common/hooks/useContainerEvents.ts
src/common/hooks/useNavigateToEditPage.ts
src/common/hooks/useRecordControls.ts
src/components/ModalDuplicateImportedResource/ModalDuplicateImportedResource.tsx
src/components/PreviewExternalResourceControls/PreviewExternalResourceControls.tsx
src/components/PreviewExternalResourcePane/PreviewExternalResourcePane.tsx
src/test/__tests__/common/hooks/useContainerEvents.test.ts
src/test/__tests__/common/hooks/useNavigateToEditPage.test.ts
src/test/__tests__/components/SearchResultEntry.test.tsx

Introduced the navigation state option `isNavigatedFromLDE`, which is set when the user navigates to the Edit page from LDE. This parameter is used to check if the user has been redirected from LDE, in order to perform the correct redirect when clicking the "Cancel" or "X" button.
[https://folio-org.atlassian.net/browse/UILD-449](https://folio-org.atlassian.net/browse/UILD-449)

UILD-449: Fix - Read-only Instance screen: 'Cancel' and X do not return user back to Inventory

---

src/common/hooks/useRecordControls.ts

https://folio-org.atlassian.net/browse/UILD-508
Remove the logic appearing modal and show an error toast instead for `already_exist` error code.

UILD-508: Error messages to display on LDE(follow-up)

---

CHANGELOG.md
src/common/hooks/useSearch.ts
src/test/__tests__/common/hooks/useSearch.test.ts

Refactor `useSearch` hook to utilize `searchParams` for `query` and `searchBy` values
[https://folio-org.atlassian.net/browse/UILD-517](https://folio-org.atlassian.net/browse/UILD-517)

UILD-517: use "searchParams" when making API calls after clicking pagination button

---

CHANGELOG.md
src/components/SearchControls/SearchControls.tsx

[UILD-535](https://folio-org.atlassian.net/browse/UILD-535)
We separated the query value from the input state to avoid triggering the increment process within the search input.

UILD-535: Search query shows slashes when entered value has quotation marks.

---

src/components/Table/Table.scss

Fixed table header cell styles: empty cells did not have the required bottom border and had excess borders.
[https://folio-org.atlassian.net/browse/UILD-545](https://folio-org.atlassian.net/browse/UILD-545)

UILD-545: Fix for styles for table header cells

---

src/components/SearchControls/SearchControls.tsx

[UILD-535](https://folio-org.atlassian.net/browse/UILD-535)
Follow-up: Fixed problem with reset button for `searchValue`

UILD-535: Search query shows slashes when entered value has quotation marks(follow-up)

---

CHANGELOG.md
src/components/Nav/Nav.tsx
src/components/SearchControls/SearchControls.tsx

[UILD-534](https://folio-org.atlassian.net/browse/UILD-534)
Fixed the problem with the double pane for `external/marc ` resources.

UILD-534: Fix double title shown when importing after marc preview is opened

---

CHANGELOG.md
src/common/services/userValues/userValues.service.ts

Fix formatting of console error message in `UserValuesService` to make it safe.
[https://folio-org.atlassian.net/browse/UILD-526](https://folio-org.atlassian.net/browse/UILD-526)

UILD-526: Fix formatting of console error message

---

CHANGELOG.md
src/views/ExternalResource/ExternalResourcePreview.tsx

Fix for External Preview: clear MARC preview state to display controls on the External Preview pane.
[https://folio-org.atlassian.net/browse/UILD-534](https://folio-org.atlassian.net/browse/UILD-534)

UILD-534: display External Preview controls

---

CHANGELOG.md
src/common/services/recordToSchemaMapping/recordToSchemaMapping.service.ts
src/common/services/schema/schemaWithDuplicates.interface.ts
src/common/services/schema/schemaWithDuplicates.service.ts
src/test/__tests__/common/services/recordToSchemaMapping/recordToSchemaMapping.service.test.ts
src/test/__tests__/common/services/schema/schemaWithDuplicates.service.test.ts

Changed a parameter for the `duplicateEntry` entry, which is used to detect if the duplication is initiated automatically during the record's loading or by the user.
Excluded record IDs from parent records to address an issue where a record contains repeatable subcomponents and this results in redundant records being created when mapping the record against the schema.
[https://folio-org.atlassian.net/browse/UILD-544](https://folio-org.atlassian.net/browse/UILD-544)

UILD-544: fix for a record with repeatable subcomponents

---

src/common/constants/import.constants.ts
src/components/Modal/Modal.tsx
src/components/ModalImport/ModalImport.tsx
src/test/__tests__/components/ModalImport.test.tsx
translations/ui-linked-data/en.json

Update modal to disable close actions during active import. Add a timeout mechanism to avoid trapping the user permanently on this screen, progress to failure view after timeout expires.

UILD-561 update

---

src/common/services/schema/schemaGenerator.service.ts
src/test/__tests__/common/services/schema/schemaGenerator.service.test.ts

This PR fixes the bug: When duplicating “Creator/Contributor of Work”, second occurrence shows “Person” type by default.
An empty option should be shown.
[https://folio-org.atlassian.net/browse/UILD-550](https://folio-org.atlassian.net/browse/UILD-550)

UILD-550: Fix - Show empty selected option by default when duplicating Creator/Contributor of Work

---

CHANGELOG.md
src/App.scss
src/common/styles/common.scss
src/components/Button/Button.scss
src/components/Dropdown/Dropdown.scss
src/components/Preview/preview.types.ts
src/components/WorkDetailsCard/WorkDetailsCard.scss
src/components/WorkDetailsCard/WorkDetailsCard.tsx

https://folio-org.atlassian.net/browse/UILD-579
This PR removes rules that disabled focus-visible indicators, updates button types to be more consistent, and aligns anchor and some button types' appearance across interaction states with Stripes. Aside from accessibility, it also updates Work titles in search results to align with UX designs.
Screenshots of tab-focused areas of concern fixed for this story, which would have had no visible indicators prior to these changes:

UILD-579: General accessibility issues

---

CHANGELOG.md
src/common/helpers/profile.helper.ts
src/common/hooks/useConfig.hook.ts
src/common/hooks/useLoadProfile.ts
src/configs/index.ts
src/configs/profiles/index.ts
src/configs/profiles/profiles.config.ts
src/store/stores/profile.ts
src/test/__tests__/common/helpers/profile.helper.test.ts
src/test/__tests__/common/hooks/useConfig.hook.test.ts
src/test/__tests__/common/hooks/useLoadProfile.hook.test.ts
src/views/Edit/Edit.tsx

Loading separate profiles for Work and Instance on the Create resource page
[https://folio-org.atlassian.net/browse/UILD-578](https://folio-org.atlassian.net/browse/UILD-578)
**Technical details:**
The Create Work page now makes a request for the Work profile. The Create Instance page makes two requests: one for the Instance profile to render the work form and another for the Work profile to render the preview section with the linked Work data.
To implement this, a new hook has been introduced to load profiles, along with a new configuration to determine the root entry of the Monograph profile. Additionally, the general logic has been updated to apply the configuration and load the required profiles.

UILD-578: use separate profiles for Work and Instance

---

src/common/constants/bibframeMapping.constants.ts
src/common/helpers/record.helper.ts
src/common/services/recordGenerator/processors/profileSchema/baseDropdownProcessor.ts
src/common/services/recordGenerator/processors/value/valueProcessor.interface.ts
src/common/services/recordGenerator/processors/value/valueProcessor.ts
src/common/services/recordGenerator/schemas/common/propertyDefinitions.ts
src/common/services/recordGenerator/schemas/profiles/monograph/work.schema.ts
src/common/services/recordGenerator/types/value.types.ts
src/test/__tests__/common/helpers/record.helper.test.ts
src/test/__tests__/common/services/recordGenerator/processors/value/valueProcessor.test.ts

This PR fixes a regression that occurred after the UI refactoring and the introduction of new record generation services.
**Fixes made:**
Updated record generation services to remove empty values ​​from the generated record.
Updated record schemas to set correct field names.
[https://folio-org.atlassian.net/browse/UILD-589](https://folio-org.atlassian.net/browse/UILD-589)

UILD-589: Fix - incorrect record generation

---

src/common/services/recordGenerator/processors/profileSchema/groupProcessor.ts
src/common/services/recordGenerator/schemas/common/schemaBuilders.ts
src/common/services/recordToSchemaMapping/recordToSchemaMapping.service.ts
src/test/__tests__/common/services/recordGenerator/processors/profileSchema/groupProcessor.test.ts
src/test/__tests__/common/services/recordGenerator/schemas/common/schemaBuilders.test.ts
src/types/recordModel.d.ts

Fixes for regression after implementing a new profile and adding a new record generation algorithm.
[https://folio-org.atlassian.net/browse/UILD-589](https://folio-org.atlassian.net/browse/UILD-589)
**Technical details:**
**Case 1:** "Creator"/"Contributor" type shows a link instead of a label on Read-only screens.
**Fix:** Stopped setting the value for the profile schema entry with the type "dropdown".
**Case 2:** "Notes about the Work"/"Notes about the Instance" fields: when type is not set and only "Note" value is set and saved, it is not shown when re-opening the resource.
**Fix:** Extended the record schema for "Notes" with the required options and extended the record generation algorithm to apply these options. This is necessary to add a default note type when the Notes value is …

UILD-589: Regression fix - generating a record with a default value

---

CHANGELOG.md
src/common/constants/bibframeMapping.constants.ts

Add "award" note  in Work section
--
Add "admin history", "biographical data", "physical Description" & "accompanying material" notes in Instance section. ("physical Description" is not shown in the attached image due to alphabetical sorting)

UILD-569: Add support for adminhist, biogdata, physical, accmat and award notes

---

CHANGELOG.md
src/common/constants/bibframeMapping.constants.ts
src/common/services/recordGenerator/schemas/common/propertyDefinitions.ts
src/common/services/recordGenerator/schemas/profiles/monograph/work.schema.ts

https://folio-org.atlassian.net/browse/UILD-594
Updated editor UI includes new, repeatable series section:
Saving the form generates a request with this structure, as detailed in https://folio-org.atlassian.net/browse/MODLD-777:

UILD-594: Add series support to editor

---

CHANGELOG.md
src/common/constants/bibframeMapping.constants.ts
src/common/services/recordGenerator/schemas/profiles/monograph/instance.schema.ts

https://folio-org.atlassian.net/browse/UILD-557
Requires profiles changes in https://github.com/folio-org/mod-linked-data/pull/257
`extent` is now treated as an object instead of a literal, adjust the UI accordingly.
Add extent values to an instance:
Which generates the following request structure:
An instance with the former extent-as-literal generates the following response:
Which can then be modified in the UI:

UILD-557: Add support for updated extent handling

---

package.json
vite.config.ts

The goal of this PR is to remove redundant file format to reduce the final package size.
A deprecated script has also been removed.

Fix: Update package.json and vite.config.ts to remove UMD format support

---

src/components/ModalChooseProfile/ModalChooseProfile.tsx
src/test/__tests__/components/ModalChooseProfile.test.tsx

[This PR](https://github.com/folio-org/ui-linked-data/pull/189) that we merged yesterday caused a problem. See the attached screen recording.
https://github.com/user-attachments/assets/15bf9edc-b408-4607-be9f-99ece4373d8b
This PR solves the problem.
Summary the change: Set the first profiles's ID as the `selectedValue` in `ModalChooseProfile` component.

UILD-573: Initialize 'selected profile' with first profile's ID

---

CHANGELOG.md
src/common/constants/bibframeMapping.constants.ts

Purpose
---
Add support for Dates of Publication note (MARC 362) in Linked Data Editor.
The "Dates of Publication note"  is equivalent to "numbering" note in Bibframe. Hence, this note will be labelled as "numbering" in the UI

UILD-606: Add support for DATES_OF_PUBLICATION_NOTE

---

src/common/constants/bibframeMapping.constants.ts

Correct this property scheme to match all others in this file.

Correct URI scheme to http

---

src/components/ProfileSelectionManager/ProfileSelectionManager.tsx
src/test/__tests__/components/ProfileSelectionManager.test.tsx

[https://folio-org.atlassian.net/browse/UILD-635](https://folio-org.atlassian.net/browse/UILD-635)
**Details:**
- When the action is 'change', the profile ID from the current record is used.
- When the action is 'set' or the modal is closed, the selected profile ID is reset to null, and the first item from the profiles list is selected.

UILD-635: Fix - use selected profile in profile selection modal

---

CHANGELOG.md
src/common/services/recordGenerator/recordGenerator.ts
src/test/__tests__/common/services/recordGenerator/recordGenerator.test.ts

Enhance reference handling in `RecordGenerator` service. 
Fixes the case: when reference check failed, then the profile ID was not added to the generated record.
[https://folio-org.atlassian.net/browse/UILD-637](https://folio-org.atlassian.net/browse/UILD-637)

UILD-637: Fix - Add profile ID to generated record

---

CHANGELOG.md
src/common/helpers/repeatableFields.helper.ts
src/test/__tests__/common/helpers/repeatableFields.helper.test.ts

https://folio-org.atlassian.net/browse/UILD-629
The Admin metadata section would previously have had button controls for adding another instance or removing if more than one were available; this change removes the buttons entirely as this section should not be repeated or removed.

UILD-629: Remove repeat button from non-repeatable group section

---

CHANGELOG.md
src/components/EditSection/DrawComponent.tsx
src/components/SimpleLookupField/SimpleLookupField.tsx
src/test/__tests__/components/EditSection.test.tsx
src/test/__tests__/components/SimpleLookupField.test.tsx

https://folio-org.atlassian.net/browse/UILD-631
This brief screen recording demonstrates the following:
1. The current multiselect behavior where choosing another value adds it to the current list
2. Compared to the new single select behavior where choosing another value replaces the existing one

UILD-631: Implement repeatable flag for simple profile type

---

src/common/services/recordGenerator/processors/profileSchema/groupProcessor.ts
src/test/__tests__/common/services/recordGenerator/processors/profileSchema/groupProcessor.test.ts

- https://folio-org.atlassian.net/browse/UILD-642 (describes bug)
- https://folio-org.atlassian.net/browse/UILD-632 (introduces repeatable literal fields)
The group processor presumes user values are returned as a list for more complex field types, but with the introduction of repeatable literal fields in a group, the implementation ends up replacing successive values in the final computed value object instead of combining them, resulting in a final DTO with just one value instead of all of them.
Update the group processor to combine multiple fields representing the same URI, only when repeatable.

UILD-642: Fix: Update group processor for repeated fields

---

src/views/Edit/Edit.tsx

[https://folio-org.atlassian.net/browse/UILD-574](https://folio-org.atlassian.net/browse/UILD-574)
Removed unused record status handling and cleaned up loading status checks in `Edit` component.
This was added to prevent unnecessary processing and API requests. In fact, this is what caused the regression.
This can be fixed by adding Zustand selectors and React Query. There are technical debt tickets for this:
[https://folio-org.atlassian.net/browse/UILD-643](https://folio-org.atlassian.net/browse/UILD-643)
[https://folio-org.atlassian.net/browse/UILD-60](https://folio-org.atlassian.net/browse/UILD-60)

UILD-574: Fix - broken Edit and Action buttons on the Edit page
